
spring:
  application.name: dubbo-provider

dubbo.service.version: 1.0.0
dubbo:
  #scan.base-packages: dubbo.service  #也可以用注解 @EnableDubbo(scanBasePackages = {"dubbo.service"})
  protocol:
    name: dubbo
    port: 12345
  registry.address: N/A  # N/A是普通服务），zookeeper://192.168.142.128:2181， nacos://${nacos.server-address}:${nacos.port}
#  provider:
#    timeout: 3000

